"""Add people_count field to Record model

Revision ID: 7266e7cab144
Revises: e6d28c839a40
Create Date: 2025-04-18 18:05:26.426135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7266e7cab144'
down_revision = 'e6d28c839a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_count', sa.Integer(), nullable=False))
        batch_op.drop_column('person_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('people_count')

    # ### end Alembic commands ###
