"""add person_count field

Revision ID: e6d28c839a40
Revises: 
Create Date: 2025-04-18 17:42:29.101509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d28c839a40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_record', schema=None) as batch_op:
        batch_op.drop_column('person_count')

    # ### end Alembic commands ###
